name: car_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^13.0.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  permission_handler: ^11.0.1
  http: ^1.1.0


  geocoding: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lock-fill.svg
    - assets/lock-unlock-fill.svg
    - assets/gas-station-fill.svg
    - assets/edit-line.svg
    - assets/roadster-fill.svg
    - assets/map-pin-line.svg
    - assets/FordEscort.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf