name: car_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^13.0.2
  flutter_svg: ^2.0.16
  permission_handler: ^11.0.1
  http: ^1.2.2
  shared_preferences: ^2.0.0
  device_preview_plus: ^2.2.3
  provider: ^6.0.3
  flutter_dotenv: ^5.2.1

  geocoding: any
  time: ^2.1.5
  flutter_riverpod: ^2.6.1
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
##Material 3 icons used
  assets:
    - assets/icons/
    - assets/img/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 400